### ISSUE TITLE
There are JavaScript errors on the page. Please contact the webmaster.

### ISSUE THREAD

**Issue by puternutt** [strangerstudios/pmpro-wp-affiliate-platform#3]
On the checkout page after selecting the membership doesn't matter if I fill in the fields or not, use Microsoft Edge or Internet Explorer,  it kicks back the error 

*(There are JavaScript errors on the page. Please contact the webmaster.)* I checked the

**Comment by andrewlimaza** [comment]
Hey @puternutt 

Are you still having this issue? I know this is just shy of 2 years old but it could be caused by another issue as there is no JavaScript loading for this Add On.

**Comment by puternutt** [comment]
The customer closed the store, couldn't resolved development issues about a year ago.
